[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mr_deepgram"
version = "1.0.0"
description = "Deepgram TTS"
requires-python = ">=3.7"
dependencies = []
